name: Build & Deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project6:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy project6-service \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/project6:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080

      - name: Show Cloud Run service URL
        run: |
          gcloud run services describe project6-service \
            --platform managed \
            --region us-central1 \
            --format="value(status.url)"
